version: '3.1'

services:
    mongo:
        image:
          mongo:latest
        ports: 
          - ${MONGO_CONNECTION_PORT}:27017
        environment: 
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        restart: 
          always
        volumes: 
          - mongodata:/data/db
volumes:
    mongodata: